//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("Model", "USADO", "AUTOMOVIL", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.AUTOMOVIL), "EVT_REPUESTO_USADO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.EVT_REPUESTO_USADO), true)]
[assembly: EdmRelationshipAttribute("Model", "PERTENECEN", "DISTRIBUIDORA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.DISTRIBUIDORA), "PERFIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.PERFIL), true)]
[assembly: EdmRelationshipAttribute("Model", "RELACION", "TALLER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TALLER), "DISTRIBUIDORA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.DISTRIBUIDORA), true)]
[assembly: EdmRelationshipAttribute("Model", "SERA_USADO", "STOCK", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.STOCK), "EVT_REPUESTO_USADO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.EVT_REPUESTO_USADO), true)]
[assembly: EdmRelationshipAttribute("Model", "POSEE", "TALLER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TALLER), "PERFIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.PERFIL), true)]
[assembly: EdmRelationshipAttribute("Model", "PERTENECIENTE", "REPUESTO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.REPUESTO), "STOCK", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.STOCK), true)]
[assembly: EdmRelationshipAttribute("Model", "TIENE", "TALLER", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.TALLER), "STOCK", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.STOCK), true)]

#endregion

namespace DAO
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Entities usando la cadena de conexión encontrada en la sección 'Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<AUTOMOVIL> AUTOMOVIL
        {
            get
            {
                if ((_AUTOMOVIL == null))
                {
                    _AUTOMOVIL = base.CreateObjectSet<AUTOMOVIL>("AUTOMOVIL");
                }
                return _AUTOMOVIL;
            }
        }
        private ObjectSet<AUTOMOVIL> _AUTOMOVIL;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DISTRIBUIDORA> DISTRIBUIDORA
        {
            get
            {
                if ((_DISTRIBUIDORA == null))
                {
                    _DISTRIBUIDORA = base.CreateObjectSet<DISTRIBUIDORA>("DISTRIBUIDORA");
                }
                return _DISTRIBUIDORA;
            }
        }
        private ObjectSet<DISTRIBUIDORA> _DISTRIBUIDORA;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<EVT_REPUESTO_USADO> EVT_REPUESTO_USADO
        {
            get
            {
                if ((_EVT_REPUESTO_USADO == null))
                {
                    _EVT_REPUESTO_USADO = base.CreateObjectSet<EVT_REPUESTO_USADO>("EVT_REPUESTO_USADO");
                }
                return _EVT_REPUESTO_USADO;
            }
        }
        private ObjectSet<EVT_REPUESTO_USADO> _EVT_REPUESTO_USADO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PERFIL> PERFIL
        {
            get
            {
                if ((_PERFIL == null))
                {
                    _PERFIL = base.CreateObjectSet<PERFIL>("PERFIL");
                }
                return _PERFIL;
            }
        }
        private ObjectSet<PERFIL> _PERFIL;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<REPUESTO> REPUESTO
        {
            get
            {
                if ((_REPUESTO == null))
                {
                    _REPUESTO = base.CreateObjectSet<REPUESTO>("REPUESTO");
                }
                return _REPUESTO;
            }
        }
        private ObjectSet<REPUESTO> _REPUESTO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<STOCK> STOCK
        {
            get
            {
                if ((_STOCK == null))
                {
                    _STOCK = base.CreateObjectSet<STOCK>("STOCK");
                }
                return _STOCK;
            }
        }
        private ObjectSet<STOCK> _STOCK;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TALLER> TALLER
        {
            get
            {
                if ((_TALLER == null))
                {
                    _TALLER = base.CreateObjectSet<TALLER>("TALLER");
                }
                return _TALLER;
            }
        }
        private ObjectSet<TALLER> _TALLER;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet AUTOMOVIL. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAUTOMOVIL(AUTOMOVIL aUTOMOVIL)
        {
            base.AddObject("AUTOMOVIL", aUTOMOVIL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DISTRIBUIDORA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDISTRIBUIDORA(DISTRIBUIDORA dISTRIBUIDORA)
        {
            base.AddObject("DISTRIBUIDORA", dISTRIBUIDORA);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet EVT_REPUESTO_USADO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEVT_REPUESTO_USADO(EVT_REPUESTO_USADO eVT_REPUESTO_USADO)
        {
            base.AddObject("EVT_REPUESTO_USADO", eVT_REPUESTO_USADO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PERFIL. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPERFIL(PERFIL pERFIL)
        {
            base.AddObject("PERFIL", pERFIL);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet REPUESTO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToREPUESTO(REPUESTO rEPUESTO)
        {
            base.AddObject("REPUESTO", rEPUESTO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet STOCK. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToSTOCK(STOCK sTOCK)
        {
            base.AddObject("STOCK", sTOCK);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TALLER. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTALLER(TALLER tALLER)
        {
            base.AddObject("TALLER", tALLER);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="AUTOMOVIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AUTOMOVIL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto AUTOMOVIL.
        /// </summary>
        /// <param name="vIN_AUTOMOVIL">Valor inicial de la propiedad VIN_AUTOMOVIL.</param>
        /// <param name="mARCA_AUTOMOVIL">Valor inicial de la propiedad MARCA_AUTOMOVIL.</param>
        /// <param name="mODELO_AUTOMOVIL">Valor inicial de la propiedad MODELO_AUTOMOVIL.</param>
        /// <param name="aÑO_AUTOMOVIL">Valor inicial de la propiedad AÑO_AUTOMOVIL.</param>
        public static AUTOMOVIL CreateAUTOMOVIL(global::System.String vIN_AUTOMOVIL, global::System.String mARCA_AUTOMOVIL, global::System.String mODELO_AUTOMOVIL, global::System.Decimal aÑO_AUTOMOVIL)
        {
            AUTOMOVIL aUTOMOVIL = new AUTOMOVIL();
            aUTOMOVIL.VIN_AUTOMOVIL = vIN_AUTOMOVIL;
            aUTOMOVIL.MARCA_AUTOMOVIL = mARCA_AUTOMOVIL;
            aUTOMOVIL.MODELO_AUTOMOVIL = mODELO_AUTOMOVIL;
            aUTOMOVIL.AÑO_AUTOMOVIL = aÑO_AUTOMOVIL;
            return aUTOMOVIL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VIN_AUTOMOVIL
        {
            get
            {
                return _VIN_AUTOMOVIL;
            }
            set
            {
                if (_VIN_AUTOMOVIL != value)
                {
                    OnVIN_AUTOMOVILChanging(value);
                    ReportPropertyChanging("VIN_AUTOMOVIL");
                    _VIN_AUTOMOVIL = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("VIN_AUTOMOVIL");
                    OnVIN_AUTOMOVILChanged();
                }
            }
        }
        private global::System.String _VIN_AUTOMOVIL;
        partial void OnVIN_AUTOMOVILChanging(global::System.String value);
        partial void OnVIN_AUTOMOVILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MARCA_AUTOMOVIL
        {
            get
            {
                return _MARCA_AUTOMOVIL;
            }
            set
            {
                OnMARCA_AUTOMOVILChanging(value);
                ReportPropertyChanging("MARCA_AUTOMOVIL");
                _MARCA_AUTOMOVIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MARCA_AUTOMOVIL");
                OnMARCA_AUTOMOVILChanged();
            }
        }
        private global::System.String _MARCA_AUTOMOVIL;
        partial void OnMARCA_AUTOMOVILChanging(global::System.String value);
        partial void OnMARCA_AUTOMOVILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MODELO_AUTOMOVIL
        {
            get
            {
                return _MODELO_AUTOMOVIL;
            }
            set
            {
                OnMODELO_AUTOMOVILChanging(value);
                ReportPropertyChanging("MODELO_AUTOMOVIL");
                _MODELO_AUTOMOVIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MODELO_AUTOMOVIL");
                OnMODELO_AUTOMOVILChanged();
            }
        }
        private global::System.String _MODELO_AUTOMOVIL;
        partial void OnMODELO_AUTOMOVILChanging(global::System.String value);
        partial void OnMODELO_AUTOMOVILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AÑO_AUTOMOVIL
        {
            get
            {
                return _AÑO_AUTOMOVIL;
            }
            set
            {
                OnAÑO_AUTOMOVILChanging(value);
                ReportPropertyChanging("AÑO_AUTOMOVIL");
                _AÑO_AUTOMOVIL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AÑO_AUTOMOVIL");
                OnAÑO_AUTOMOVILChanged();
            }
        }
        private global::System.Decimal _AÑO_AUTOMOVIL;
        partial void OnAÑO_AUTOMOVILChanging(global::System.Decimal value);
        partial void OnAÑO_AUTOMOVILChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "USADO", "EVT_REPUESTO_USADO")]
        public EntityCollection<EVT_REPUESTO_USADO> EVT_REPUESTO_USADO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EVT_REPUESTO_USADO>("Model.USADO", "EVT_REPUESTO_USADO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EVT_REPUESTO_USADO>("Model.USADO", "EVT_REPUESTO_USADO", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="DISTRIBUIDORA")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DISTRIBUIDORA : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DISTRIBUIDORA.
        /// </summary>
        /// <param name="rUT_DIST">Valor inicial de la propiedad RUT_DIST.</param>
        /// <param name="nOMBRE_DIST">Valor inicial de la propiedad NOMBRE_DIST.</param>
        /// <param name="dIRECCION_DIST">Valor inicial de la propiedad DIRECCION_DIST.</param>
        /// <param name="tELEFONO_DIST">Valor inicial de la propiedad TELEFONO_DIST.</param>
        /// <param name="rUT_TALLER">Valor inicial de la propiedad RUT_TALLER.</param>
        public static DISTRIBUIDORA CreateDISTRIBUIDORA(global::System.String rUT_DIST, global::System.String nOMBRE_DIST, global::System.String dIRECCION_DIST, global::System.String tELEFONO_DIST, global::System.String rUT_TALLER)
        {
            DISTRIBUIDORA dISTRIBUIDORA = new DISTRIBUIDORA();
            dISTRIBUIDORA.RUT_DIST = rUT_DIST;
            dISTRIBUIDORA.NOMBRE_DIST = nOMBRE_DIST;
            dISTRIBUIDORA.DIRECCION_DIST = dIRECCION_DIST;
            dISTRIBUIDORA.TELEFONO_DIST = tELEFONO_DIST;
            dISTRIBUIDORA.RUT_TALLER = rUT_TALLER;
            return dISTRIBUIDORA;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_DIST
        {
            get
            {
                return _RUT_DIST;
            }
            set
            {
                if (_RUT_DIST != value)
                {
                    OnRUT_DISTChanging(value);
                    ReportPropertyChanging("RUT_DIST");
                    _RUT_DIST = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RUT_DIST");
                    OnRUT_DISTChanged();
                }
            }
        }
        private global::System.String _RUT_DIST;
        partial void OnRUT_DISTChanging(global::System.String value);
        partial void OnRUT_DISTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE_DIST
        {
            get
            {
                return _NOMBRE_DIST;
            }
            set
            {
                OnNOMBRE_DISTChanging(value);
                ReportPropertyChanging("NOMBRE_DIST");
                _NOMBRE_DIST = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE_DIST");
                OnNOMBRE_DISTChanged();
            }
        }
        private global::System.String _NOMBRE_DIST;
        partial void OnNOMBRE_DISTChanging(global::System.String value);
        partial void OnNOMBRE_DISTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION_DIST
        {
            get
            {
                return _DIRECCION_DIST;
            }
            set
            {
                OnDIRECCION_DISTChanging(value);
                ReportPropertyChanging("DIRECCION_DIST");
                _DIRECCION_DIST = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DIRECCION_DIST");
                OnDIRECCION_DISTChanged();
            }
        }
        private global::System.String _DIRECCION_DIST;
        partial void OnDIRECCION_DISTChanging(global::System.String value);
        partial void OnDIRECCION_DISTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TELEFONO_DIST
        {
            get
            {
                return _TELEFONO_DIST;
            }
            set
            {
                OnTELEFONO_DISTChanging(value);
                ReportPropertyChanging("TELEFONO_DIST");
                _TELEFONO_DIST = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TELEFONO_DIST");
                OnTELEFONO_DISTChanged();
            }
        }
        private global::System.String _TELEFONO_DIST;
        partial void OnTELEFONO_DISTChanging(global::System.String value);
        partial void OnTELEFONO_DISTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_TALLER
        {
            get
            {
                return _RUT_TALLER;
            }
            set
            {
                OnRUT_TALLERChanging(value);
                ReportPropertyChanging("RUT_TALLER");
                _RUT_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT_TALLER");
                OnRUT_TALLERChanged();
            }
        }
        private global::System.String _RUT_TALLER;
        partial void OnRUT_TALLERChanging(global::System.String value);
        partial void OnRUT_TALLERChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "PERTENECEN", "PERFIL")]
        public EntityCollection<PERFIL> PERFIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERFIL>("Model.PERTENECEN", "PERFIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERFIL>("Model.PERTENECEN", "PERFIL", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "RELACION", "TALLER")]
        public TALLER TALLER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.RELACION", "TALLER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.RELACION", "TALLER").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TALLER> TALLERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.RELACION", "TALLER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TALLER>("Model.RELACION", "TALLER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="EVT_REPUESTO_USADO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EVT_REPUESTO_USADO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto EVT_REPUESTO_USADO.
        /// </summary>
        /// <param name="iD_REP_USADO">Valor inicial de la propiedad ID_REP_USADO.</param>
        /// <param name="fECHA_USO">Valor inicial de la propiedad FECHA_USO.</param>
        /// <param name="pRECIO_UNITARIO">Valor inicial de la propiedad PRECIO_UNITARIO.</param>
        /// <param name="iD_STOCK">Valor inicial de la propiedad ID_STOCK.</param>
        /// <param name="vIN_AUTOMOVIL">Valor inicial de la propiedad VIN_AUTOMOVIL.</param>
        public static EVT_REPUESTO_USADO CreateEVT_REPUESTO_USADO(global::System.String iD_REP_USADO, global::System.DateTime fECHA_USO, global::System.Decimal pRECIO_UNITARIO, global::System.String iD_STOCK, global::System.String vIN_AUTOMOVIL)
        {
            EVT_REPUESTO_USADO eVT_REPUESTO_USADO = new EVT_REPUESTO_USADO();
            eVT_REPUESTO_USADO.ID_REP_USADO = iD_REP_USADO;
            eVT_REPUESTO_USADO.FECHA_USO = fECHA_USO;
            eVT_REPUESTO_USADO.PRECIO_UNITARIO = pRECIO_UNITARIO;
            eVT_REPUESTO_USADO.ID_STOCK = iD_STOCK;
            eVT_REPUESTO_USADO.VIN_AUTOMOVIL = vIN_AUTOMOVIL;
            return eVT_REPUESTO_USADO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_REP_USADO
        {
            get
            {
                return _ID_REP_USADO;
            }
            set
            {
                if (_ID_REP_USADO != value)
                {
                    OnID_REP_USADOChanging(value);
                    ReportPropertyChanging("ID_REP_USADO");
                    _ID_REP_USADO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_REP_USADO");
                    OnID_REP_USADOChanged();
                }
            }
        }
        private global::System.String _ID_REP_USADO;
        partial void OnID_REP_USADOChanging(global::System.String value);
        partial void OnID_REP_USADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_USO
        {
            get
            {
                return _FECHA_USO;
            }
            set
            {
                OnFECHA_USOChanging(value);
                ReportPropertyChanging("FECHA_USO");
                _FECHA_USO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_USO");
                OnFECHA_USOChanged();
            }
        }
        private global::System.DateTime _FECHA_USO;
        partial void OnFECHA_USOChanging(global::System.DateTime value);
        partial void OnFECHA_USOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRECIO_UNITARIO
        {
            get
            {
                return _PRECIO_UNITARIO;
            }
            set
            {
                OnPRECIO_UNITARIOChanging(value);
                ReportPropertyChanging("PRECIO_UNITARIO");
                _PRECIO_UNITARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRECIO_UNITARIO");
                OnPRECIO_UNITARIOChanged();
            }
        }
        private global::System.Decimal _PRECIO_UNITARIO;
        partial void OnPRECIO_UNITARIOChanging(global::System.Decimal value);
        partial void OnPRECIO_UNITARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_STOCK
        {
            get
            {
                return _ID_STOCK;
            }
            set
            {
                OnID_STOCKChanging(value);
                ReportPropertyChanging("ID_STOCK");
                _ID_STOCK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_STOCK");
                OnID_STOCKChanged();
            }
        }
        private global::System.String _ID_STOCK;
        partial void OnID_STOCKChanging(global::System.String value);
        partial void OnID_STOCKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VIN_AUTOMOVIL
        {
            get
            {
                return _VIN_AUTOMOVIL;
            }
            set
            {
                OnVIN_AUTOMOVILChanging(value);
                ReportPropertyChanging("VIN_AUTOMOVIL");
                _VIN_AUTOMOVIL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VIN_AUTOMOVIL");
                OnVIN_AUTOMOVILChanged();
            }
        }
        private global::System.String _VIN_AUTOMOVIL;
        partial void OnVIN_AUTOMOVILChanging(global::System.String value);
        partial void OnVIN_AUTOMOVILChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CANTIDAD_SALIDA
        {
            get
            {
                return _CANTIDAD_SALIDA;
            }
            set
            {
                OnCANTIDAD_SALIDAChanging(value);
                ReportPropertyChanging("CANTIDAD_SALIDA");
                _CANTIDAD_SALIDA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CANTIDAD_SALIDA");
                OnCANTIDAD_SALIDAChanged();
            }
        }
        private Nullable<global::System.Decimal> _CANTIDAD_SALIDA;
        partial void OnCANTIDAD_SALIDAChanging(Nullable<global::System.Decimal> value);
        partial void OnCANTIDAD_SALIDAChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "USADO", "AUTOMOVIL")]
        public AUTOMOVIL AUTOMOVIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AUTOMOVIL>("Model.USADO", "AUTOMOVIL").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AUTOMOVIL>("Model.USADO", "AUTOMOVIL").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AUTOMOVIL> AUTOMOVILReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AUTOMOVIL>("Model.USADO", "AUTOMOVIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AUTOMOVIL>("Model.USADO", "AUTOMOVIL", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SERA_USADO", "STOCK")]
        public STOCK STOCK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STOCK>("Model.SERA_USADO", "STOCK").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STOCK>("Model.SERA_USADO", "STOCK").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<STOCK> STOCKReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STOCK>("Model.SERA_USADO", "STOCK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<STOCK>("Model.SERA_USADO", "STOCK", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="PERFIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PERFIL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PERFIL.
        /// </summary>
        /// <param name="uSERNAME">Valor inicial de la propiedad USERNAME.</param>
        /// <param name="pASSWORD">Valor inicial de la propiedad PASSWORD.</param>
        /// <param name="tIPO_PERMISO">Valor inicial de la propiedad TIPO_PERMISO.</param>
        /// <param name="rUT_DIST">Valor inicial de la propiedad RUT_DIST.</param>
        /// <param name="rUT_TALLER">Valor inicial de la propiedad RUT_TALLER.</param>
        public static PERFIL CreatePERFIL(global::System.String uSERNAME, global::System.String pASSWORD, global::System.Decimal tIPO_PERMISO, global::System.String rUT_DIST, global::System.String rUT_TALLER)
        {
            PERFIL pERFIL = new PERFIL();
            pERFIL.USERNAME = uSERNAME;
            pERFIL.PASSWORD = pASSWORD;
            pERFIL.TIPO_PERMISO = tIPO_PERMISO;
            pERFIL.RUT_DIST = rUT_DIST;
            pERFIL.RUT_TALLER = rUT_TALLER;
            return pERFIL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USERNAME
        {
            get
            {
                return _USERNAME;
            }
            set
            {
                if (_USERNAME != value)
                {
                    OnUSERNAMEChanging(value);
                    ReportPropertyChanging("USERNAME");
                    _USERNAME = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USERNAME");
                    OnUSERNAMEChanged();
                }
            }
        }
        private global::System.String _USERNAME;
        partial void OnUSERNAMEChanging(global::System.String value);
        partial void OnUSERNAMEChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PASSWORD
        {
            get
            {
                return _PASSWORD;
            }
            set
            {
                OnPASSWORDChanging(value);
                ReportPropertyChanging("PASSWORD");
                _PASSWORD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PASSWORD");
                OnPASSWORDChanged();
            }
        }
        private global::System.String _PASSWORD;
        partial void OnPASSWORDChanging(global::System.String value);
        partial void OnPASSWORDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TIPO_PERMISO
        {
            get
            {
                return _TIPO_PERMISO;
            }
            set
            {
                OnTIPO_PERMISOChanging(value);
                ReportPropertyChanging("TIPO_PERMISO");
                _TIPO_PERMISO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TIPO_PERMISO");
                OnTIPO_PERMISOChanged();
            }
        }
        private global::System.Decimal _TIPO_PERMISO;
        partial void OnTIPO_PERMISOChanging(global::System.Decimal value);
        partial void OnTIPO_PERMISOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_DIST
        {
            get
            {
                return _RUT_DIST;
            }
            set
            {
                OnRUT_DISTChanging(value);
                ReportPropertyChanging("RUT_DIST");
                _RUT_DIST = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT_DIST");
                OnRUT_DISTChanged();
            }
        }
        private global::System.String _RUT_DIST;
        partial void OnRUT_DISTChanging(global::System.String value);
        partial void OnRUT_DISTChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_TALLER
        {
            get
            {
                return _RUT_TALLER;
            }
            set
            {
                OnRUT_TALLERChanging(value);
                ReportPropertyChanging("RUT_TALLER");
                _RUT_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT_TALLER");
                OnRUT_TALLERChanged();
            }
        }
        private global::System.String _RUT_TALLER;
        partial void OnRUT_TALLERChanging(global::System.String value);
        partial void OnRUT_TALLERChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "PERTENECEN", "DISTRIBUIDORA")]
        public DISTRIBUIDORA DISTRIBUIDORA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRIBUIDORA>("Model.PERTENECEN", "DISTRIBUIDORA").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRIBUIDORA>("Model.PERTENECEN", "DISTRIBUIDORA").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DISTRIBUIDORA> DISTRIBUIDORAReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISTRIBUIDORA>("Model.PERTENECEN", "DISTRIBUIDORA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DISTRIBUIDORA>("Model.PERTENECEN", "DISTRIBUIDORA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "POSEE", "TALLER")]
        public TALLER TALLER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.POSEE", "TALLER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.POSEE", "TALLER").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TALLER> TALLERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.POSEE", "TALLER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TALLER>("Model.POSEE", "TALLER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="REPUESTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class REPUESTO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto REPUESTO.
        /// </summary>
        /// <param name="iD_REPUESTO">Valor inicial de la propiedad ID_REPUESTO.</param>
        /// <param name="mARCA">Valor inicial de la propiedad MARCA.</param>
        /// <param name="cALIDAD">Valor inicial de la propiedad CALIDAD.</param>
        /// <param name="oRIGEN">Valor inicial de la propiedad ORIGEN.</param>
        /// <param name="eSTADO">Valor inicial de la propiedad ESTADO.</param>
        public static REPUESTO CreateREPUESTO(global::System.String iD_REPUESTO, global::System.String mARCA, global::System.String cALIDAD, global::System.String oRIGEN, global::System.String eSTADO)
        {
            REPUESTO rEPUESTO = new REPUESTO();
            rEPUESTO.ID_REPUESTO = iD_REPUESTO;
            rEPUESTO.MARCA = mARCA;
            rEPUESTO.CALIDAD = cALIDAD;
            rEPUESTO.ORIGEN = oRIGEN;
            rEPUESTO.ESTADO = eSTADO;
            return rEPUESTO;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_REPUESTO
        {
            get
            {
                return _ID_REPUESTO;
            }
            set
            {
                if (_ID_REPUESTO != value)
                {
                    OnID_REPUESTOChanging(value);
                    ReportPropertyChanging("ID_REPUESTO");
                    _ID_REPUESTO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_REPUESTO");
                    OnID_REPUESTOChanged();
                }
            }
        }
        private global::System.String _ID_REPUESTO;
        partial void OnID_REPUESTOChanging(global::System.String value);
        partial void OnID_REPUESTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MARCA
        {
            get
            {
                return _MARCA;
            }
            set
            {
                OnMARCAChanging(value);
                ReportPropertyChanging("MARCA");
                _MARCA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MARCA");
                OnMARCAChanged();
            }
        }
        private global::System.String _MARCA;
        partial void OnMARCAChanging(global::System.String value);
        partial void OnMARCAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CALIDAD
        {
            get
            {
                return _CALIDAD;
            }
            set
            {
                OnCALIDADChanging(value);
                ReportPropertyChanging("CALIDAD");
                _CALIDAD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CALIDAD");
                OnCALIDADChanged();
            }
        }
        private global::System.String _CALIDAD;
        partial void OnCALIDADChanging(global::System.String value);
        partial void OnCALIDADChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ORIGEN
        {
            get
            {
                return _ORIGEN;
            }
            set
            {
                OnORIGENChanging(value);
                ReportPropertyChanging("ORIGEN");
                _ORIGEN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ORIGEN");
                OnORIGENChanged();
            }
        }
        private global::System.String _ORIGEN;
        partial void OnORIGENChanging(global::System.String value);
        partial void OnORIGENChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private global::System.String _ESTADO;
        partial void OnESTADOChanging(global::System.String value);
        partial void OnESTADOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE_REPUESTO
        {
            get
            {
                return _NOMBRE_REPUESTO;
            }
            set
            {
                OnNOMBRE_REPUESTOChanging(value);
                ReportPropertyChanging("NOMBRE_REPUESTO");
                _NOMBRE_REPUESTO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBRE_REPUESTO");
                OnNOMBRE_REPUESTOChanged();
            }
        }
        private global::System.String _NOMBRE_REPUESTO;
        partial void OnNOMBRE_REPUESTOChanging(global::System.String value);
        partial void OnNOMBRE_REPUESTOChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "PERTENECIENTE", "STOCK")]
        public EntityCollection<STOCK> STOCK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<STOCK>("Model.PERTENECIENTE", "STOCK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<STOCK>("Model.PERTENECIENTE", "STOCK", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="STOCK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class STOCK : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto STOCK.
        /// </summary>
        /// <param name="iD_STOCK">Valor inicial de la propiedad ID_STOCK.</param>
        /// <param name="cANTIDAD_STOCK">Valor inicial de la propiedad CANTIDAD_STOCK.</param>
        /// <param name="fECHA_LLEGADA">Valor inicial de la propiedad FECHA_LLEGADA.</param>
        /// <param name="iD_REPUESTO">Valor inicial de la propiedad ID_REPUESTO.</param>
        /// <param name="rUT_TALLER">Valor inicial de la propiedad RUT_TALLER.</param>
        public static STOCK CreateSTOCK(global::System.String iD_STOCK, global::System.Decimal cANTIDAD_STOCK, global::System.DateTime fECHA_LLEGADA, global::System.String iD_REPUESTO, global::System.String rUT_TALLER)
        {
            STOCK sTOCK = new STOCK();
            sTOCK.ID_STOCK = iD_STOCK;
            sTOCK.CANTIDAD_STOCK = cANTIDAD_STOCK;
            sTOCK.FECHA_LLEGADA = fECHA_LLEGADA;
            sTOCK.ID_REPUESTO = iD_REPUESTO;
            sTOCK.RUT_TALLER = rUT_TALLER;
            return sTOCK;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_STOCK
        {
            get
            {
                return _ID_STOCK;
            }
            set
            {
                if (_ID_STOCK != value)
                {
                    OnID_STOCKChanging(value);
                    ReportPropertyChanging("ID_STOCK");
                    _ID_STOCK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_STOCK");
                    OnID_STOCKChanged();
                }
            }
        }
        private global::System.String _ID_STOCK;
        partial void OnID_STOCKChanging(global::System.String value);
        partial void OnID_STOCKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CANTIDAD_STOCK
        {
            get
            {
                return _CANTIDAD_STOCK;
            }
            set
            {
                OnCANTIDAD_STOCKChanging(value);
                ReportPropertyChanging("CANTIDAD_STOCK");
                _CANTIDAD_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CANTIDAD_STOCK");
                OnCANTIDAD_STOCKChanged();
            }
        }
        private global::System.Decimal _CANTIDAD_STOCK;
        partial void OnCANTIDAD_STOCKChanging(global::System.Decimal value);
        partial void OnCANTIDAD_STOCKChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FECHA_LLEGADA
        {
            get
            {
                return _FECHA_LLEGADA;
            }
            set
            {
                OnFECHA_LLEGADAChanging(value);
                ReportPropertyChanging("FECHA_LLEGADA");
                _FECHA_LLEGADA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FECHA_LLEGADA");
                OnFECHA_LLEGADAChanged();
            }
        }
        private global::System.DateTime _FECHA_LLEGADA;
        partial void OnFECHA_LLEGADAChanging(global::System.DateTime value);
        partial void OnFECHA_LLEGADAChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_REPUESTO
        {
            get
            {
                return _ID_REPUESTO;
            }
            set
            {
                OnID_REPUESTOChanging(value);
                ReportPropertyChanging("ID_REPUESTO");
                _ID_REPUESTO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_REPUESTO");
                OnID_REPUESTOChanged();
            }
        }
        private global::System.String _ID_REPUESTO;
        partial void OnID_REPUESTOChanging(global::System.String value);
        partial void OnID_REPUESTOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_TALLER
        {
            get
            {
                return _RUT_TALLER;
            }
            set
            {
                OnRUT_TALLERChanging(value);
                ReportPropertyChanging("RUT_TALLER");
                _RUT_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RUT_TALLER");
                OnRUT_TALLERChanged();
            }
        }
        private global::System.String _RUT_TALLER;
        partial void OnRUT_TALLERChanging(global::System.String value);
        partial void OnRUT_TALLERChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SERA_USADO", "EVT_REPUESTO_USADO")]
        public EntityCollection<EVT_REPUESTO_USADO> EVT_REPUESTO_USADO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EVT_REPUESTO_USADO>("Model.SERA_USADO", "EVT_REPUESTO_USADO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EVT_REPUESTO_USADO>("Model.SERA_USADO", "EVT_REPUESTO_USADO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "PERTENECIENTE", "REPUESTO")]
        public REPUESTO REPUESTO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<REPUESTO>("Model.PERTENECIENTE", "REPUESTO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<REPUESTO>("Model.PERTENECIENTE", "REPUESTO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<REPUESTO> REPUESTOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<REPUESTO>("Model.PERTENECIENTE", "REPUESTO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<REPUESTO>("Model.PERTENECIENTE", "REPUESTO", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TIENE", "TALLER")]
        public TALLER TALLER
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.TIENE", "TALLER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.TIENE", "TALLER").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TALLER> TALLERReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TALLER>("Model.TIENE", "TALLER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TALLER>("Model.TIENE", "TALLER", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TALLER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TALLER : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TALLER.
        /// </summary>
        /// <param name="rUT_TALLER">Valor inicial de la propiedad RUT_TALLER.</param>
        /// <param name="nOMBRE_TALLER">Valor inicial de la propiedad NOMBRE_TALLER.</param>
        /// <param name="rOL_TALLER">Valor inicial de la propiedad ROL_TALLER.</param>
        /// <param name="dIRECCION_TALLER">Valor inicial de la propiedad DIRECCION_TALLER.</param>
        /// <param name="tELEFONO_TALLER">Valor inicial de la propiedad TELEFONO_TALLER.</param>
        public static TALLER CreateTALLER(global::System.String rUT_TALLER, global::System.String nOMBRE_TALLER, global::System.String rOL_TALLER, global::System.String dIRECCION_TALLER, global::System.String tELEFONO_TALLER)
        {
            TALLER tALLER = new TALLER();
            tALLER.RUT_TALLER = rUT_TALLER;
            tALLER.NOMBRE_TALLER = nOMBRE_TALLER;
            tALLER.ROL_TALLER = rOL_TALLER;
            tALLER.DIRECCION_TALLER = dIRECCION_TALLER;
            tALLER.TELEFONO_TALLER = tELEFONO_TALLER;
            return tALLER;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RUT_TALLER
        {
            get
            {
                return _RUT_TALLER;
            }
            set
            {
                if (_RUT_TALLER != value)
                {
                    OnRUT_TALLERChanging(value);
                    ReportPropertyChanging("RUT_TALLER");
                    _RUT_TALLER = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RUT_TALLER");
                    OnRUT_TALLERChanged();
                }
            }
        }
        private global::System.String _RUT_TALLER;
        partial void OnRUT_TALLERChanging(global::System.String value);
        partial void OnRUT_TALLERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRE_TALLER
        {
            get
            {
                return _NOMBRE_TALLER;
            }
            set
            {
                OnNOMBRE_TALLERChanging(value);
                ReportPropertyChanging("NOMBRE_TALLER");
                _NOMBRE_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRE_TALLER");
                OnNOMBRE_TALLERChanged();
            }
        }
        private global::System.String _NOMBRE_TALLER;
        partial void OnNOMBRE_TALLERChanging(global::System.String value);
        partial void OnNOMBRE_TALLERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ROL_TALLER
        {
            get
            {
                return _ROL_TALLER;
            }
            set
            {
                OnROL_TALLERChanging(value);
                ReportPropertyChanging("ROL_TALLER");
                _ROL_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ROL_TALLER");
                OnROL_TALLERChanged();
            }
        }
        private global::System.String _ROL_TALLER;
        partial void OnROL_TALLERChanging(global::System.String value);
        partial void OnROL_TALLERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DIRECCION_TALLER
        {
            get
            {
                return _DIRECCION_TALLER;
            }
            set
            {
                OnDIRECCION_TALLERChanging(value);
                ReportPropertyChanging("DIRECCION_TALLER");
                _DIRECCION_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DIRECCION_TALLER");
                OnDIRECCION_TALLERChanged();
            }
        }
        private global::System.String _DIRECCION_TALLER;
        partial void OnDIRECCION_TALLERChanging(global::System.String value);
        partial void OnDIRECCION_TALLERChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TELEFONO_TALLER
        {
            get
            {
                return _TELEFONO_TALLER;
            }
            set
            {
                OnTELEFONO_TALLERChanging(value);
                ReportPropertyChanging("TELEFONO_TALLER");
                _TELEFONO_TALLER = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TELEFONO_TALLER");
                OnTELEFONO_TALLERChanged();
            }
        }
        private global::System.String _TELEFONO_TALLER;
        partial void OnTELEFONO_TALLERChanging(global::System.String value);
        partial void OnTELEFONO_TALLERChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "RELACION", "DISTRIBUIDORA")]
        public EntityCollection<DISTRIBUIDORA> DISTRIBUIDORA
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DISTRIBUIDORA>("Model.RELACION", "DISTRIBUIDORA");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DISTRIBUIDORA>("Model.RELACION", "DISTRIBUIDORA", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "POSEE", "PERFIL")]
        public EntityCollection<PERFIL> PERFIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PERFIL>("Model.POSEE", "PERFIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PERFIL>("Model.POSEE", "PERFIL", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "TIENE", "STOCK")]
        public EntityCollection<STOCK> STOCK
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<STOCK>("Model.TIENE", "STOCK");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<STOCK>("Model.TIENE", "STOCK", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
